### ISSUE TITLE
Update and compile fails

### ISSUE THREAD

**Issue by daveharrisuk** [obdevel/CBUS#6]
Arduino IDE (1.8.13 on ubuntu20) advised updates and updated CBUS libraries.
CBUS 1.1.14, CBUS2515 1.1.12, CBUSconfig 1.1.10, CBUSLED 1.1.6, CBUSSwitch 1.1.7
My app compile errors now - include file not found.
Found issue in /arduino/libraries/CBUS/src/CBUSParams.h line 37
"#include <CBUSconfig.h>   // 4may21 DH edit, was <CBUSConfig.h>"
Compile now works.

Dave

**Comment by obdevel** [comment]
Thanks Dave. Fixed in next release. As I said in my note, macOS is case-aware but not case-sensitive. More Linux testing required !
